### ISSUE TITLE
Client is not thread safe

### ISSUE THREAD

**Issue by jonmcewen** [klarna/kco_rest_java#7]
If used in a multi-threaded environment, the following exception can occur:

com.sun.jersey.api.client.ClientHandlerException: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
at com.sun.jersey.api.client.Client.handle(Client.java:652)
at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
at com.klarna.rest.api.BaseResource.post(BaseResource.java:123)
at com.klarna.rest.api.DefaultCapture.create(DefaultCapture.java:45)

I would suggest that the client should use a PoolingHttpClientConnectionManager by default

**Comment by jonmcewen** [comment]
PR https://github.com/klarna/kco_rest_java/pull/8

**Comment by alexions** [comment]
It's almost 1 year... Thank you for the PR. Merged to master.

In spite of the fact, that ThreadSafeClientConnectionManager is deprecated now, it is ok for the current situation.
